"""delete constraints nullable = false search_session.apartment_ids

Revision ID: 15e2749ed150
Revises: 560d2562519e
Create Date: 2025-08-01 15:04:25.783103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e2749ed150'
down_revision: Union[str, Sequence[str], None] = '560d2562519e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_status_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_apartment_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_user_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'booking_types', ['status_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'apartments', ['apartment_id'], ['id'], source_schema='public', referent_schema='apartments', ondelete='CASCADE')
    op.drop_constraint(op.f('search_sessions_user_id_fkey'), 'search_sessions', type_='foreignkey')
    op.drop_constraint(op.f('search_sessions_session_id_fkey'), 'search_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'search_sessions', 'sessions', ['session_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'search_sessions', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET DEFAULT')
    op.drop_constraint(op.f('apartments_owner_id_fkey'), 'apartments', schema='apartments', type_='foreignkey')
    op.create_foreign_key(None, 'apartments', 'users', ['owner_id'], ['id'], source_schema='apartments', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apartments', schema='apartments', type_='foreignkey')
    op.create_foreign_key(op.f('apartments_owner_id_fkey'), 'apartments', 'users', ['owner_id'], ['id'], source_schema='apartments', ondelete='CASCADE')
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'], ondelete='SET DEFAULT')
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'search_sessions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'search_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('search_sessions_session_id_fkey'), 'search_sessions', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('search_sessions_user_id_fkey'), 'search_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_user_id_fkey'), 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bookings_apartment_id_fkey'), 'bookings', 'apartments', ['apartment_id'], ['id'], referent_schema='apartments', ondelete='CASCADE')
    op.create_foreign_key(op.f('bookings_status_id_fkey'), 'bookings', 'booking_types', ['status_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
