"""complit migration prod backup autogenerate

Revision ID: d6b2baffd95a
Revises: 157e6fdec0a7
Create Date: 2025-10-16 07:18:36.392442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b2baffd95a'
down_revision: Union[str, Sequence[str], None] = '157e6fdec0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('booking_chat_booking_id_fkey'), 'booking_chat', type_='foreignkey')
    op.drop_constraint(op.f('booking_chat_sender_tg_id_fkey'), 'booking_chat', type_='foreignkey')
    op.create_foreign_key(None, 'booking_chat', 'bookings', ['booking_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'booking_chat', 'users', ['sender_tg_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('bookings_tg_user_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_apartment_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_status_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'apartments', ['apartment_id'], ['id'], source_schema='public', referent_schema='apartments', ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'users', ['tg_user_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'booking_types', ['status_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('search_sessions_tg_user_id_fkey'), 'search_sessions', type_='foreignkey')
    op.drop_constraint(op.f('search_sessions_session_id_fkey'), 'search_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'search_sessions', 'sessions', ['session_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'search_sessions', 'users', ['tg_user_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('sessions_role_id_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_tg_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET DEFAULT')
    op.create_foreign_key(None, 'sessions', 'users', ['tg_user_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('users_source_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'sources', ['source_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint(op.f('apartments_owner_tg_id_fkey'), 'apartments', schema='apartments', type_='foreignkey')
    op.create_foreign_key(None, 'apartments', 'users', ['owner_tg_id'], ['tg_user_id'], source_schema='apartments', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apartments', schema='apartments', type_='foreignkey')
    op.create_foreign_key(op.f('apartments_owner_tg_id_fkey'), 'apartments', 'users', ['owner_tg_id'], ['tg_user_id'], source_schema='apartments', ondelete='CASCADE')
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('users_source_id_fkey'), 'users', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_tg_user_id_fkey'), 'sessions', 'users', ['tg_user_id'], ['tg_user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('sessions_role_id_fkey'), 'sessions', 'roles', ['role_id'], ['id'], ondelete='SET DEFAULT')
    op.drop_constraint(None, 'search_sessions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'search_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('search_sessions_session_id_fkey'), 'search_sessions', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('search_sessions_tg_user_id_fkey'), 'search_sessions', 'users', ['tg_user_id'], ['tg_user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_status_id_fkey'), 'bookings', 'booking_types', ['status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bookings_apartment_id_fkey'), 'bookings', 'apartments', ['apartment_id'], ['id'], referent_schema='apartments', ondelete='CASCADE')
    op.create_foreign_key(op.f('bookings_tg_user_id_fkey'), 'bookings', 'users', ['tg_user_id'], ['tg_user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'booking_chat', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'booking_chat', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('booking_chat_sender_tg_id_fkey'), 'booking_chat', 'users', ['sender_tg_id'], ['tg_user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('booking_chat_booking_id_fkey'), 'booking_chat', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
