"""initial autogenerate new_server_test_bot

Revision ID: fcf08babfd22
Revises: 1aef50a5b0a8
Create Date: 2025-10-13 09:08:39.432715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcf08babfd22'
down_revision: Union[str, Sequence[str], None] = '1aef50a5b0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_unique_constraint(None, 'users', ['tg_user_id'], schema='public')
    op.drop_column('sessions','last_action')
    op.add_column('sessions', sa.Column('last_action', type_=postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BIGINT(), nullable=True),
    sa.Column('suffix', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suffix'),
    sa.UniqueConstraint('tg_user_id'),
    schema='public'
    )
    op.create_table('search_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BIGINT(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('apartment_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('current_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['public.sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tg_user_id'], ['public.users.tg_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_search_sessions_id'), 'search_sessions', ['id'], unique=False, schema='public')
    op.create_table('booking_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('sender_tg_id', sa.BIGINT(), nullable=False),
    sa.Column('message_text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['public.bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_tg_id'], ['public.users.tg_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_booking_chat_id'), 'booking_chat', ['id'], unique=False, schema='public')
    op.add_column('bookings', sa.Column('tg_user_id', sa.BIGINT(), nullable=False))
    op.add_column('bookings', sa.Column('check_in', sa.Date(), nullable=False))
    op.add_column('bookings', sa.Column('check_out', sa.Date(), nullable=False))
    op.add_column('bookings', sa.Column('decline_reason', sa.String(length=255), nullable=True))
    op.create_index('idx_booking_apartment_dates', 'bookings', ['apartment_id', 'check_in', 'check_out'], unique=False, schema='public')
    op.create_index(op.f('ix_public_bookings_check_in'), 'bookings', ['check_in'], unique=False, schema='public')
    op.create_index(op.f('ix_public_bookings_check_out'), 'bookings', ['check_out'], unique=False, schema='public')
    op.drop_constraint(op.f('bookings_status_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_apartment_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_user_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'apartments', ['apartment_id'], ['id'], source_schema='public', referent_schema='apartments', ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'booking_types', ['status_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'bookings', 'users', ['tg_user_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('bookings', 'user_id')
    op.drop_column('bookings', 'start_date')
    op.drop_column('bookings', 'end_date')
    op.add_column('sessions', sa.Column('tg_user_id', sa.BIGINT(), nullable=False))
    op.add_column('sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('role_id', sa.Integer(), server_default=sa.text('1'), nullable=False))

    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    #op.create_unique_constraint(None, 'users', ['tg_user_id'], schema='public')
    op.create_foreign_key(None, 'sessions', 'users', ['tg_user_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'sessions', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET DEFAULT')
    op.drop_column('sessions', 'user_id')
    op.drop_column('sessions', 'tg_bot_id')
    op.drop_column('sessions', 'last_interaction')
    op.add_column('users', sa.Column('firstname', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_bot', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('source_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'tg_user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('uq_name_role'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_phone_role'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_tg_user_role'), 'users', type_='unique')
#   op.create_unique_constraint(None, 'users', ['tg_user_id'], schema='public')
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'sources', ['source_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_column('users', 'role_id')
    op.add_column('apartments', sa.Column('short_address', sa.String(length=100), nullable=False), schema='apartments')
    op.add_column('apartments', sa.Column('owner_tg_id', sa.BIGINT(), nullable=False), schema='apartments')
    op.add_column('apartments', sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='apartments')
    op.add_column('apartments', sa.Column('reward', sa.Numeric(precision=4, scale=2), server_default='7.00', nullable=True), schema='apartments')
    op.add_column('apartments', sa.Column('deleted_by', sa.BIGINT(), nullable=True), schema='apartments')
    op.add_column('apartments', sa.Column('is_draft', sa.Boolean(), server_default=sa.text('true'), nullable=False), schema='apartments')
    op.drop_constraint(op.f('apartments_owner_id_fkey'), 'apartments', schema='apartments', type_='foreignkey')
    op.create_foreign_key(None, 'apartments', 'users', ['owner_tg_id'], ['tg_user_id'], source_schema='apartments', referent_schema='public', ondelete='CASCADE')
    op.drop_column('apartments', 'owner_id', schema='apartments')
    op.alter_column('images', 'tg_file_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               schema='media')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("sessions", "last_action")
    op.add_column(
        "sessions",
        sa.Column("last_action", sa.Text(), nullable=True),
    )
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'tg_file_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='media')
    op.add_column('apartments', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='apartments')
    op.drop_constraint(None, 'apartments', schema='apartments', type_='foreignkey')
    op.create_foreign_key(op.f('apartments_owner_id_fkey'), 'apartments', 'users', ['owner_id'], ['id'], source_schema='apartments', ondelete='CASCADE')
    op.drop_column('apartments', 'is_draft', schema='apartments')
    op.drop_column('apartments', 'deleted_by', schema='apartments')
    op.drop_column('apartments', 'reward', schema='apartments')
    op.drop_column('apartments', 'verified', schema='apartments')
    op.drop_column('apartments', 'owner_tg_id', schema='apartments')
    op.drop_column('apartments', 'short_address', schema='apartments')
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'], ondelete='SET DEFAULT')
    op.drop_constraint(None, 'users', schema='public', type_='unique')
    op.create_unique_constraint(op.f('uq_tg_user_role'), 'users', ['tg_user_id', 'role_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_phone_role'), 'users', ['phone_number', 'role_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_name_role'), 'users', ['username', 'role_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'tg_user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'source_id')
    op.drop_column('users', 'is_bot')
    op.drop_column('users', 'firstname')
    op.add_column('sessions', sa.Column('last_interaction', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('tg_bot_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.drop_column('sessions', 'role_id')
    op.drop_column('sessions', 'updated_at')
    op.drop_column('sessions', 'tg_user_id')
    op.add_column('bookings', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_user_id_fkey'), 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bookings_apartment_id_fkey'), 'bookings', 'apartments', ['apartment_id'], ['id'], referent_schema='apartments', ondelete='CASCADE')
    op.create_foreign_key(op.f('bookings_status_id_fkey'), 'bookings', 'booking_types', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_bookings_check_out'), table_name='bookings', schema='public')
    op.drop_index(op.f('ix_public_bookings_check_in'), table_name='bookings', schema='public')
    op.drop_index('idx_booking_apartment_dates', table_name='bookings', schema='public')
    op.drop_column('bookings', 'decline_reason')
    op.drop_column('bookings', 'check_out')
    op.drop_column('bookings', 'check_in')
    op.drop_column('bookings', 'tg_user_id')
    op.drop_index(op.f('ix_public_booking_chat_id'), table_name='booking_chat', schema='public')
    op.drop_table('booking_chat', schema='public')
    op.drop_index(op.f('ix_public_search_sessions_id'), table_name='search_sessions', schema='public')
    op.drop_table('search_sessions', schema='public')
    op.drop_table('sources', schema='public')
    # ### end Alembic commands ###
